# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.

package myprimitive;
use base qw(Exporter);
use base qw(DynaLoader);
package myprimitivec;
bootstrap myprimitive;
package myprimitive;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package myprimitive;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package myprimitive;

*dot_product = *myprimitivec::dot_product;
*vector_add = *myprimitivec::vector_add;
*rotate_arrow = *myprimitivec::rotate_arrow;
*free = *myprimitivec::free;
*new_Vector = *myprimitivec::new_Vector;
*vector_print = *myprimitivec::vector_print;

# ------- VARIABLE STUBS --------

package myprimitive;

1;
